### ISSUE TITLE
install broken

### ISSUE THREAD

**Issue by eldon** [bukzor/hodor#1]
```
» pip install hodor
Downloading/unpacking hodor
  Downloading hodor-0.tar.gz
  Running setup.py (path:/nail/home/eldon/trees/yelp/dead_code/virtualenv_run/build/hodor/setup.py) egg_info for package hodor
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/nail/home/eldon/trees/yelp/dead_code/virtualenv_run/build/hodor/setup.py", line 8, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/nail/home/eldon/trees/yelp/dead_code/virtualenv_run/build/hodor/setup.py", line 8, in <module>

    long_description=open('README.md').read(),

IOError: [Errno 2] No such file or directory: 'README.md'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /nail/home/eldon/trees/yelp/dead_code/virtualenv_run/build/hodor
Storing debug log for failure in /nail/home/eldon/.pip/pip.log
```

**Comment by eldon** [comment]
first!

**Comment by bukzor** [comment]
Fixed in 1!0.

https://pypi.python.org/pypi/hodor
